apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: cluster-workflow-nmap-template
spec:
  entrypoint: nmap-template
  arguments:
    parameters:
      - name: url
        value: "scanme.nmap.org"
  workflowTemplateRef:
    name: cluster-workflow-nmap-template
    clusterScope: true
