apiVersion: v1
kind: Pod
metadata:
 name: filestore-pod
spec:
 containers:
 - name: filestore-pod-container
   image: alpine
   volumeMounts:
   - mountPath: /storage
     name: filestore
 volumes:
 - name: filestore
   persistentVolumeClaim:
     claimName: fileserver-claim
     readOnly: false
